export const KOMMUNER = [
  { id: "oslo", name: "Oslo" },
  { id: "bergen", name: "Bergen" },
  { id: "trondheim", name: "Trondheim" },
  { id: "stavanger", name: "Stavanger" },
  { id: "drammen", name: "Drammen" },
  { id: "kristiansand", name: "Kristiansand" },
  { id: "tromso", name: "Tromsø" },
  { id: "fredrikstad", name: "Fredrikstad" },
  { id: "sandnes", name: "Sandnes" },
  { id: "sarpsborg", name: "Sarpsborg" },
  { id: "bodo", name: "Bodø" },
  { id: "alesund", name: "Ålesund" },
  { id: "sandefjord", name: "Sandefjord" },
  { id: "larvik", name: "Larvik" },
  { id: "tonsberg", name: "Tønsberg" },
  { id: "halden", name: "Halden" },
  { id: "moss", name: "Moss" },
  { id: "hamar", name: "Hamar" },
  { id: "lillehammer", name: "Lillehammer" },
  { id: "gjovik", name: "Gjøvik" },
];
